#this compose file is solely for watchtower and the workflowjs. 
#CAUTION: the github-to-dockerhub.sh is not yet implemented
 
services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  express:
    image: mohammadrezat/workflowjs
    ports:
      - 8080:8080
