
name: Release Version checkout
on: [push]
jobs:
  Builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout repository for update
        uses: actions/checkout@v4

      - 
        name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mohammadrezat/workflowjs:latest




